### ISSUE TITLE
Add Link to logo

### ISSUE THREAD

**Issue by AryanNanda17** [AryanNanda17/NonStop-Lofi-Vibe-Generator#55]
On the homepage, add a link to the logo so that whenever someone clicks on it, the page refreshes and they return to the same homepage.
<img width="1440" alt="Screenshot 2024-10-03 at 7 55 55 AM" src="https://github.com/user-attachments/assets/e46e9c06-459e-46f4-aba6-74e6ac6bdd61">

It can simply be done using `<a href="/">logo.img</a>`

**Comment by fudgemasterultra** [comment]
@AryanNanda17 Looks like a good first issue, and I'll need to get the environment setup. Mind if I take this one?

**Comment by AryanNanda17** [comment]
Hello @fudgemasterultra, 
Go ahead with it!

**Comment by AryanNanda17** [comment]
@fudgemasterultra, also, it would be really great and motivating for our team if you could star this repo so that this project reaches more people. Thanks again for your interest. I am assigning this to you

**Comment by fudgemasterultra** [comment]
@AryanNanda17 Do you want it to refresh the page on clicking or redirect the user back to the `/` route?
Right now it looks like we use the Link element and have that guide the user to the `/` route, and the reason it isn't refreshing the page is because of the way the Link property works. We can change it to an anchor element, but there is a bit of a jarring white screen then back to the app.  

Also I have stared the app. :)

**Comment by ParamThakkar123** [comment]
@fudgemasterultra we want it to redirect the user back to `/` route on clicking the logo

**Comment by fudgemasterultra** [comment]
@ParamThakkar123 This has been fixed in PR[#56](https://github.com/AryanNanda17/NonStop-Lofi-Vibe-Generator/pull/56)

**Comment by ParamThakkar123** [comment]
Okay, @AryanNanda17 just take a look. Things are working as expected so maybe we can merge this after you approve these changes.
